<a href="https://colab.research.google.com/github/MiguelFigueroa02/MCPI_Student_Repo/blob/main/courses/1-Semester/fundamentals%20of%20statistics/Projects%20/Notebooks/Basic_Genetic_Algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.metrics import make_scorer, matthews_corrcoef
from sklearn.datasets import make_classification

In [2]:
mcc_scorer = make_scorer(matthews_corrcoef)

In [3]:
def evaluacion_individual(mask, X, y):
  n_features = int(mask.sum())

  if n_features == 0 or n_features> 4:
    return -1.0

  X_subset = X[:, mask.astype(bool)]

  model = LogisticRegression(
      solver="lbfgs",
      max_iter=5000
  )

  cv = StratifiedKFold(
      n_splits=5,
      shuffle=True,
      random_state=42
  )

  scores = cross_val_score(
      model,
      X_subset,
      y,
      cv=cv,
      scoring=mcc_scorer
  )

  return scores.mean()

In [4]:
def random_individual(n_features=10, max_features=4):
  while True:
    mask = np.random.randint(
        0,2,size=n_features
    )

    if 1<=mask.sum()<=max_features:
      return mask

In [5]:
X, y = make_classification(
    n_samples=30,
    n_features=10,
    n_informative=4,
    n_redundant=1,
    n_classes=3,
    n_clusters_per_class=1,
    class_sep=1.4,
    random_state=42
)

In [6]:
feature_names = [
    "M1", "M2", "M3", "M4", "M5",
    "M6", "M7", "M8", "M9", "M10"
]

In [7]:
pd.DataFrame(data=X, columns=feature_names)

,M1,M2,M3,M4,M5,M6,M7,M8,M9,M10
0,1.361819,-0.498407,-1.545566,-0.617896,-1.639730,-0.324395,1.096796,2.113112,-2.583375,0.524609
1,1.851821,0.183856,-1.189108,-1.898610,-2.379375,0.577897,-1.548829,-0.343129,-2.608636,2.134641
2,-0.992763,-0.699378,0.114098,-0.428498,-0.367851,-0.418509,0.591316,-0.883079,-2.574548,-0.111419
3,2.830116,-0.127735,-2.521714,-2.274976,-3.143601,-1.560557,0.195346,-0.555945,-1.673921,2.000348
4,0.376054,1.032513,0.034135,-1.940207,-1.732366,-1.034402,0.926233,0.607839,-3.350033,0.204283
5,-2.226592,2.273345,-0.717736,-1.598312,-0.733708,0.146975,0.418119,-1.886528,-0.915593,0.539609
6,2.707088,-1.551434,-1.899340,-1.750087,-2.751818,-0.510493,-1.801888,0.467717,-2.600558,-0.732951
7,-0.060140,-0.765509,-1.272960,0.280098,-0.496092,0.422314,-0.374522,-1.291216,-1.493868,-1.307914
8,-1.497601,-2.216761,1.450308,-2.228592,-0.312343,1.389566,0.448649,-0.078732,0.537656,1.870424
9,1.668255,-2.254159,1.718716,1.796849,0.863319,-2.456593,0.790594,0.632852,-1.963554,-0.076532


In [8]:
Individual = random_individual()
print(Individual)
selected = [feature_names[i] for i, value in enumerate(Individual) if value ==1]
print(selected)

[1 0 0 0 0 1 0 1 1 0]
['M1', 'M6', 'M8', 'M9']


In [9]:
score = evaluacion_individual(Individual, X, y)
print(score)

0.3745770242898356


In [10]:
poblacion = [random_individual() for _ in range(30)]

In [11]:
poblacion

[array([0, 1, 0, 0, 1, 0, 1, 0, 0, 1]),
 array([1, 0, 1, 0, 0, 0, 0, 0, 1, 1]),
 array([1, 1, 0, 1, 0, 0, 0, 1, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 1, 0, 1, 0, 0]),
 array([0, 1, 1, 1, 0, 0, 0, 0, 0, 0]),
 array([1, 1, 0, 0, 0, 0, 1, 1, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([1, 0, 0, 0, 0, 1, 0, 1, 0, 1]),
 array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0]),
 array([0, 0, 0, 1, 0, 1, 0, 0, 1, 1]),
 array([0, 1, 1, 0, 0, 0, 1, 0, 0, 0]),
 array([1, 0, 0, 0, 1, 0, 0, 1, 0, 1]),
 array([0, 0, 0, 1, 0, 0, 1, 1, 0, 0]),
 array([0, 1, 1, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 1, 0, 1, 0, 1, 0, 0, 0, 0]),
 array([1, 1, 0, 0, 0, 0, 0, 0, 1, 1]),
 array([1, 0, 1, 0, 0, 1, 0, 0, 1, 0]),
 array([1, 1, 0, 0, 0, 0, 1, 0, 1, 0]),
 array([0, 0, 1, 1, 0, 0, 1, 1, 0, 0]),
 array([1, 0, 0, 0, 0, 1, 1, 0, 0, 1]),
 array([1, 0, 0, 1, 0, 0, 0, 0, 1, 0]),
 array([1, 0, 1, 1, 1, 0, 0, 0, 0, 0]),
 array([0, 1, 1, 0, 1, 0, 0, 0, 1, 0]),
 array([0, 0, 1, 0, 0, 0, 1, 0, 0, 1]),


In [12]:
evaluaciones = [evaluacion_individual(ind, X, y) for ind in poblacion]
evaluaciones

[np.float64(0.317100954340678),
 np.float64(0.7442798883961064),
 np.float64(0.27363264736703374),
 np.float64(0.43581426785941507),
 np.float64(0.38760999803597834),
 np.float64(0.30889318714683733),
 np.float64(0.4343215646904345),
 np.float64(0.3835909710727057),
 np.float64(0.26111648393354675),
 np.float64(0.24515301754878283),
 np.float64(0.05222329678670935),
 np.float64(0.2901678377637934),
 np.float64(0.6266795614405123),
 np.float64(0.31885151085250935),
 np.float64(0.2901678377637934),
 np.float64(-0.16346054035628882),
 np.float64(0.06875848718346902),
 np.float64(0.7876099980359783),
 np.float64(0.2866656211131765),
 np.float64(0.47107480763921866),
 np.float64(0.4990610249106308),
 np.float64(0.3179071339297075),
 np.float64(0.7223537275031262),
 np.float64(0.5495996111222016),
 np.float64(0.33687940441824954),
 np.float64(0.7079542120574682),
 np.float64(0.3765865377714719),
 np.float64(0.5946144313372121),
 np.float64(0.3044465935734187),
 np.float64(0.7223537275031262)

In [13]:
concate = pd.DataFrame({'máscara': poblacion, 'evaluación': evaluaciones})
concate.sort_values('evaluación', ascending=False)

,máscara,evaluación
17,"[1, 0, 1, 0, 0, 1, 0, 0, 1, 0]",0.787610
1,"[1, 0, 1, 0, 0, 0, 0, 0, 1, 1]",0.744280
22,"[1, 0, 1, 1, 1, 0, 0, 0, 0, 0]",0.722354
29,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 1]",0.722354
25,"[0, 0, 1, 0, 1, 0, 0, 0, 1, 1]",0.707954
12,"[1, 0, 0, 0, 1, 0, 0, 1, 0, 1]",0.626680
27,"[0, 0, 1, 1, 0, 0, 0, 0, 1, 0]",0.594614
23,"[0, 1, 1, 0, 1, 0, 0, 0, 1, 0]",0.549600
20,"[1, 0, 0, 0, 0, 1, 1, 0, 0, 1]",0.499061
19,"[0, 0, 1, 1, 0, 0, 1, 1, 0, 0]",0.471075


In [14]:
for ind, value in zip(poblacion, evaluaciones):

  print(ind, value)

[0 1 0 0 1 0 1 0 0 1] 0.317100954340678
[1 0 1 0 0 0 0 0 1 1] 0.7442798883961064
[1 1 0 1 0 0 0 1 0 0] 0.27363264736703374
[1 0 0 0 0 0 0 0 0 0] 0.43581426785941507
[0 0 0 0 1 1 0 1 0 0] 0.38760999803597834
[0 1 1 1 0 0 0 0 0 0] 0.30889318714683733
[1 1 0 0 0 0 1 1 0 0] 0.4343215646904345
[1 0 0 0 0 0 0 1 0 0] 0.3835909710727057
[1 0 0 0 0 1 0 1 0 1] 0.26111648393354675
[0 1 0 0 1 0 1 0 1 0] 0.24515301754878283
[0 0 0 1 0 1 0 0 1 1] 0.05222329678670935
[0 1 1 0 0 0 1 0 0 0] 0.2901678377637934
[1 0 0 0 1 0 0 1 0 1] 0.6266795614405123
[0 0 0 1 0 0 1 1 0 0] 0.31885151085250935
[0 1 1 0 0 0 1 0 0 0] 0.2901678377637934
[0 1 0 1 0 1 0 0 0 0] -0.16346054035628882
[1 1 0 0 0 0 0 0 1 1] 0.06875848718346902
[1 0 1 0 0 1 0 0 1 0] 0.7876099980359783
[1 1 0 0 0 0 1 0 1 0] 0.2866656211131765
[0 0 1 1 0 0 1 1 0 0] 0.47107480763921866
[1 0 0 0 0 1 1 0 0 1] 0.4990610249106308
[1 0 0 1 0 0 0 0 1 0] 0.3179071339297075
[1 0 1 1 1 0 0 0 0 0] 0.7223537275031262
[0 1 1 0 1 0 0 0 1 0] 0.5495996111222016
[0 0 

In [15]:
def torneo(poblacion, evaluaciones, k=3):
  indices = np.random.choice(
      len(poblacion),
      size=k,
      replace=False
  )
  print(indices)
  winner = indices[np.argmax(
      [evaluaciones[i] for i in indices]
  )]
  print(evaluaciones[winner])


  return poblacion[winner].copy()

In [16]:
ganador = torneo(poblacion, evaluaciones)
ganador

[11 20  9]
0.4990610249106308


array([1, 0, 0, 0, 0, 1, 1, 0, 0, 1])

In [22]:
def two_point_crossover(a,b):
  points = sorted(
      np.random.choice(
          np.arange(1, len(a)),
          size = 2,
          replace=False
    )
  )
  p1, p2 = points
  child1=a.copy()
  child2=b.copy()

  child1[p1:p2], child2[p1:p2] = (
      a[p1:p2],
      b[p1:p2]
  )

  return child1, child2


In [23]:
def bit_flip_mutation(individual, indpb=0.2):
  child = individual.copy()
  for i in range(len(child)):
    if np.random.rand() < indpb:
      child[i] = 1 - child[i]

    return child

In [24]:
np.random.seed(1)

population_size = 30
n_generations = 12

crossover_probability = 0.5
mutation_probability = 0.2

population = [
    random_individual()
    for _ in range(population_size)
]

history = []

for generation in range(n_generations + 1):

    # 1. Evaluar población
    fitnesses = np.array([
        evaluacion_individual(ind, X, y)
        for ind in population
    ])

    # 2. Identificar mejor individuo
    best_index = np.argmax(fitnesses)

    best_individual = (
        population[best_index]
    )

    best_fitness = (
        fitnesses[best_index]
    )

    mean_fitness = (
        fitnesses.mean()
    )

    history.append({
        "generation": generation,
        "best_MCC": best_fitness,
        "mean_MCC": mean_fitness
    })

    print(
        f"Generation {generation:02d} | "
        f"Best MCC = {best_fitness:.3f} | "
        f"Mean MCC = {mean_fitness:.3f}"
    )

    # No crear nueva población después
    # de la última generación
    if generation == n_generations:
        break

    # 3. Elitismo:
    # conservar el mejor
    new_population = [
        best_individual.copy()
    ]

    # 4. Generar descendientes
    while len(new_population) < population_size:

        parent1 = torneo(
            population,
            fitnesses
        )

        parent2 = torneo(
            population,
            fitnesses
        )

        child1 = parent1.copy()
        child2 = parent2.copy()

        # Crossover
        if np.random.rand() < crossover_probability:

            child1, child2 = (
                two_point_crossover(
                    parent1,
                    parent2
                )
            )

        # Mutation
        if np.random.rand() < mutation_probability:
            child1 = bit_flip_mutation(
                child1
            )

        if np.random.rand() < mutation_probability:
            child2 = bit_flip_mutation(
                child2
            )

        # Reparar si excede máximo
        if child1.sum() > 4:
            ones = np.where(child1 == 1)[0]

            while child1.sum() > 4:
                child1[
                    np.random.choice(ones)
                ] = 0
                ones = np.where(child1 == 1)[0]

        if child1.sum() == 0:
            child1[
                np.random.randint(10)
            ] = 1

        if child2.sum() > 4:
            ones = np.where(child2 == 1)[0]

            while child2.sum() > 4:
                child2[
                    np.random.choice(ones)
                ] = 0
                ones = np.where(child2 == 1)[0]

        if child2.sum() == 0:
            child2[
                np.random.randint(10)
            ] = 1

        new_population.append(child1)

        if len(new_population) < population_size:
            new_population.append(child2)

    population = new_population

Generation 00 | Best MCC = 0.722 | Mean MCC = 0.334
[ 2 28  4]
0.3566698903601281
[28 23 24]
0.4430227444311138
[ 9  0 21]
0.4133397807202561
[25 23 22]
0.4430227444311138
[14  3  6]
0.7223537275031262
[28 24  4]
0.3566698903601281
[11 18 16]
0.5946144313372121
[16  3  2]
0.7223537275031262
[ 9 12 28]
0.7223537275031262
[20 28 10]
0.4935492947783776
[23 11 12]
0.7223537275031262
[ 2 22 28]
0.3566698903601281
[11  7 29]
0.7223537275031262
[ 9 28 25]
0.3566698903601281
[20 10  6]
0.4935492947783776
[10 21  1]
0.4133397807202561
[16  8 29]
0.7223537275031262
[ 1 12 29]
0.7223537275031262
[20 21 28]
0.4935492947783776
[ 8 22 27]
0.5044465935734187
[18  3 22]
0.7223537275031262
[12  1 23]
0.7223537275031262
[18 16 24]
0.5946144313372121
[19 12  5]
0.7223537275031262
[28  7 21]
0.4133397807202561
[ 3 22 23]
0.7223537275031262
[ 0 28  9]
0.3566698903601281
[ 8 24  6]
0.08647361370701845
[10 29 21]
0.7223537275031262
[21 26  4]
0.4288098345581813
Generation 01 | Best MCC = 0.722 | Mean MCC = 0